const countries = {
    "ne-NP": "Nepali (नेपाली)",
    "en-US": "English (USA)",
    "hi-IN": "Hindi (हिन्दी)",
    "ja-JP": "Japanese",
    "ko-KR": "Korean",
    "zh-CN": "Chinese",
    "es-ES": "Spanish",
    "fr-FR": "French",
    "de-DE": "German",
    "ru-RU": "Russian",
    "ar-SA": "Arabic",
    "pt-PT": "Portuguese",
    "it-IT": "Italian",
    "bn-IN": "Bengali",
    "ur-PK": "Urdu",
    "pa-IN": "Punjabi",
    "ta-LK": "Tamil",
    "th-TH": "Thai",
    "vi-VN": "Vietnamese",
    "id-ID": "Indonesian",
    "tr-TR": "Turkish",
    "ms-MY": "Malay",
    "my-MM": "Burmese",
    "km-KH": "Khmer",
    "si-LK": "Sinhala",
    "uk-UA": "Ukrainian",
    "pl-PL": "Polish",
    "ro-RO": "Romanian",
    "nl-NL": "Dutch",
    "el-GR": "Greek",
    "sv-SE": "Swedish",
    "no-NO": "Norwegian",
    "da-DK": "Danish",
    "fi-FI": "Finnish",
    "cs-CZ": "Czech",
    "hu-HU": "Hungarian",
    "sk-SK": "Slovak",
    "he-IL": "Hebrew",
    "af-ZA": "Afrikaans",
    "bg-BG": "Bulgarian",
    "hr-HR": "Croatian",
    "sr-RS": "Serbian",
    "fil-PH": "Filipino",
    "is-IS": "Icelandic",
    "la-VA": "Latin"
};
